### ISSUE TITLE
Pretrained PSPNet on ResNet101

### ISSUE THREAD

**Issue by Sam1224** [Wyxdm/AMNet#6]
Could you please release the pretrained PSPNet models with ResNet101? Both BAM and PSPNet only provide with VGG16's and ResNet50's versions.

**Comment by Wyxdm** [comment]
Please refer to [checkpoints](https://rec.ustc.edu.cn/share/8bf363d0-e67e-11ee-a4f5-cf47a77fd4a5)

**Comment by Sam1224** [comment]
Thanks for your quick apply!
